exp_name: 'mimic-diff'
gpu_id: [0]
logger:
    display_id: 9908
model:
    change_detector:
        input_dim: 2052
        feat_dim: 1026
        att_dim: 1024
        att_head: 4
        nongt_dim: 52
        spa_label_num: 11
        sem_label_num: 3
        dir_num: 2
        pos_emb_dim: 64
        coef_sem: 0.333
        coef_spa: 0.333
        num_hidden_layers: 2
    speaker:
        embed_input_dim: 6144
        embed_dim: 1024
        input_dim: 1024 # equals to change_detector.att_dim
        seq_length: 90
#        vocab_size: 39

data:
    dataset: 'rcc_dataset_mimic'
    vocab_json: "/cluster/project7/MIMIC/dataset_synced/dataset_synced/vqadiff/data/vocab_mimic_VQA.json"
    h5_label_file: "/cluster/project7/MIMIC/dataset_synced/dataset_synced/vqadiff/data/VQA_mimic_dataset.h5"
    splits_json: "/cluster/project7/MIMIC/dataset_synced/dataset_synced/vqadiff/data/splits_mimic_VQA.json"
    num_workers: 0
    train:
        batch_size: 64
        empty_image: false
    val:
        seq_per_img: 1
    test:
        seq_per_img: 1
train:
    max_iter: 40000 # original 30000
    max_epoch: 20 # original 15
    snapshot_interval: 2000
    optim:
        type: 'adam'
        lr: 0.00005
        weight_decay: 0.0
        step_size: 15 #epoch
        gamma: 0.1

